/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Planilla;

import ClasesElRey.TextAreaRenderer;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.net.HttpURLConnection;
import java.net.URL;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import org.json.JSONObject;

/**
 *
 * @author it
 */
public class Nomina_Empleados extends javax.swing.JInternalFrame {

    private TableRowSorter<DefaultTableModel> sorter;
    private DefaultTableModel modelo;
    private ArrayList<ClassNomina> result;
    private String modoOperacion = ""; // "NUEVO" o "EDITAR"


    /**
     * Creates new form Empleados
     */
    public Nomina_Empleados()  throws Exception{
        initComponents();
        ListarEmpleados();
        
        TablaEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
    @Override
    public void mouseClicked(java.awt.event.MouseEvent evt) {
        int row = TablaEmpleados.getSelectedRow();
        if (row >= 0) {
            String codigo = TablaEmpleados.getValueAt(row, 0).toString();
            buscarEmpleado(Integer.parseInt(codigo));
            habilitarCampos(false);
        }
    }
});
    
btnNuevo.addActionListener(e -> {
    modoOperacion = "NUEVO";
    limpiarCampos();
    habilitarCampos(true);
    generarSiguienteCodigo();
});

btnEditar.addActionListener(e -> {
    if (CODIGO.getText().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Seleccione un empleado.");
        return;
    }

    modoOperacion = "EDITAR";
    habilitarCampos(true);
});

btnGuardar.addActionListener(e -> {
    if (modoOperacion.equals("NUEVO")) {
        guardarNuevo();
    } else if (modoOperacion.equals("EDITAR")) {
        guardarEdicion();
    } else {
        JOptionPane.showMessageDialog(null, "No hay operación seleccionada.");
    }
});


        
        
        
        
    }

    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    private void ListarEmpleados() throws Exception {
        result = ApiPlanilla.ListarEmpleados();
        RecargarTabla(result);
    }

    private void RecargarTabla(ArrayList<ClassNomina> list) {
        Object[][] datos = new Object[list.size()][2];
        int i = 0;
        for (ClassNomina t : list) {
            datos[i][0] = t.getCodigo();
            datos[i][1] = t.getNombre();
            i++;
        }

        modelo = new DefaultTableModel(
                datos,
                new String[]{"CODIGO", "NOMBRES"}
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                // Permitir la edición solo de la columna descripción
                return column == 1;
            }
        };

        TablaEmpleados.setModel(modelo);

        // ⭐ IMPORTANTE → Asignar sorter
        sorter = new TableRowSorter<>(modelo);
        TablaEmpleados.setRowSorter(sorter);

        TablaEmpleados.getColumnModel().getColumn(1).setCellRenderer(new TextAreaRenderer());
        TablaEmpleados.getColumn("CODIGO").setPreferredWidth(-20);
        TablaEmpleados.getColumn("NOMBRES").setPreferredWidth(255);
    }
    
    ///////////////////botones
    
    public void habilitarCampos(boolean estado) {
    NOMBRE.setEnabled(estado);
    DPI.setEnabled(estado);
    PUESTO.setEnabled(estado);
    SALARIO.setEnabled(estado);
    BONIFICACION.setEnabled(estado);
    IGSS.setEnabled(estado);
    FECHAIN.setEnabled(estado);

    chkPlanilla.setEnabled(estado);
    chkContrato.setEnabled(estado);
}
/////////////////////limpiar
    
    public void limpiarCampos() {
    CODIGO.setText("");
    NOMBRE.setText("");
    DPI.setText("");
    PUESTO.setText("");
    SALARIO.setText("");
    BONIFICACION.setText("");
    IGSS.setText("");
    FECHAIN.setDate(null);
    chkPlanilla.setSelected(false);
    chkContrato.setSelected(false);
}

    
    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TablaEmpleados = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        CODIGO = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        NOMBRE = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        DPI = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        PUESTO = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        chkContrato = new javax.swing.JCheckBox();
        chkPlanilla = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        SALARIO = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        BONIFICACION = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        IGSS = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        FECHAIN = new com.toedter.calendar.JDateChooser();

        setClosable(true);

        TablaEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "CODIGO", "NOMBRE"
            }
        ));
        jScrollPane1.setViewportView(TablaEmpleados);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("CODIGO");

        CODIGO.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CODIGO.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("NOMBRE");

        NOMBRE.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NOMBRE.setEnabled(false);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("DPI");

        DPI.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        DPI.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("PUESTO");

        PUESTO.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        PUESTO.setEnabled(false);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("TIPO CONTRATACION");

        chkContrato.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        chkContrato.setForeground(new java.awt.Color(102, 102, 255));
        chkContrato.setText("CONTRATO");
        chkContrato.setEnabled(false);
        chkContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkContratoActionPerformed(evt);
            }
        });

        chkPlanilla.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        chkPlanilla.setForeground(new java.awt.Color(102, 102, 255));
        chkPlanilla.setText("PLANILLA");
        chkPlanilla.setEnabled(false);
        chkPlanilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkPlanillaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CODIGO, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
                    .addComponent(NOMBRE)
                    .addComponent(DPI)
                    .addComponent(PUESTO)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(chkContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(chkPlanilla, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel10))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CODIGO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NOMBRE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DPI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PUESTO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkContrato)
                    .addComponent(chkPlanilla))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnGuardar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/save2.png"))); // NOI18N
        btnGuardar.setText("GUARDAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnNuevo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/New.png"))); // NOI18N
        btnNuevo.setText("NUEVO");

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/ComponenteImagenes/Cancel.png"))); // NOI18N
        jButton3.setText("CANCELAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        btnEditar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/edit2.png"))); // NOI18N
        btnEditar.setText("EDITAR");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("SALARIO");

        SALARIO.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        SALARIO.setEnabled(false);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("BONIFICACION");

        BONIFICACION.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BONIFICACION.setEnabled(false);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("IGSS");

        IGSS.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        IGSS.setEnabled(false);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("FECHA INGRESO");

        FECHAIN.setEnabled(false);
        FECHAIN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BONIFICACION)
                    .addComponent(SALARIO, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(FECHAIN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(IGSS, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(0, 243, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SALARIO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BONIFICACION, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IGSS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FECHAIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkPlanillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkPlanillaActionPerformed
        chkContrato.setSelected(false);
    }//GEN-LAST:event_chkPlanillaActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       habilitarCampos(false);
        limpiarCampos();
        try {
            ListarEmpleados();
        } catch (Exception ex) {
            Logger.getLogger(Nomina_Empleados.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void chkContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkContratoActionPerformed
        chkPlanilla.setSelected(false);
    }//GEN-LAST:event_chkContratoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BONIFICACION;
    private javax.swing.JTextField CODIGO;
    private javax.swing.JTextField DPI;
    private com.toedter.calendar.JDateChooser FECHAIN;
    private javax.swing.JTextField IGSS;
    private javax.swing.JTextField NOMBRE;
    private javax.swing.JTextField PUESTO;
    private javax.swing.JTextField SALARIO;
    private javax.swing.JTable TablaEmpleados;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JCheckBox chkContrato;
    private javax.swing.JCheckBox chkPlanilla;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    public void buscarEmpleado(int codigo) {
    try {
        URL url = new URL("http://40.233.19.196/nominapega/empleados/" + codigo);
        HttpURLConnection con = (HttpURLConnection) url.openConnection();

        con.setRequestMethod("GET");
        con.setRequestProperty("Accept", "application/json");

        int code = con.getResponseCode();
        if (code != 200) {
            JOptionPane.showMessageDialog(null, "No se encontró el empleado");
            return;
        }

        BufferedReader br = new BufferedReader(new InputStreamReader(con.getInputStream(), "utf-8"));
        StringBuilder response = new StringBuilder();
        String line;

        while ((line = br.readLine()) != null) {
            response.append(line.trim());
        }

        JSONObject json = new JSONObject(response.toString());

        // Llenar campos
        CODIGO.setText(json.optString("CODIGO"));
        NOMBRE.setText(json.optString("NOMBRES"));
        DPI.setText(json.optString("DPI"));
        PUESTO.setText(json.optString("PUESTO"));
        SALARIO.setText(json.optString("SALARIO"));
        BONIFICACION.setText(json.optString("BONIFICACION"));
        IGSS.setText(json.optString("IGSS"));

        // FECHA INGRESO
        String fechaIngreso = json.optString("FECHA_INGRESO");
        if (!fechaIngreso.isEmpty() && !fechaIngreso.equals("null")) {
            SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
            java.util.Date fecha = df.parse(fechaIngreso);
            FECHAIN.setDate(fecha);
        } else {
            FECHAIN.setDate(null);
        }

        // Checkboxes
        int tipo = json.optInt("TIPO_CONTRATACION", 0);

        if (tipo == 1) {      // PLANILLA
            chkPlanilla.setSelected(true);
            chkContrato.setSelected(false);
        } else if (tipo == 2) { // CONTRATO
            chkPlanilla.setSelected(false);
            chkContrato.setSelected(true);
        } else {
            chkPlanilla.setSelected(false);
            chkContrato.setSelected(false);
        }

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error al buscar empleado: " + e.getMessage());
    }
}
    
public void generarSiguienteCodigo() {
    try {
        URL url = new URL("http://40.233.19.196/nominapega/empleados/ultimoCodigo");
        HttpURLConnection con = (HttpURLConnection) url.openConnection();
        con.setRequestMethod("GET");

        BufferedReader br = new BufferedReader(new InputStreamReader(con.getInputStream(), "utf-8"));
        String json = br.readLine();

        JSONObject obj = new JSONObject(json);
        int ultimo = obj.optInt("ultimo", 0);

        int siguiente = ultimo + 1;

        CODIGO.setText(String.valueOf(siguiente));

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "No se pudo obtener el siguiente código");
    }
}

public void guardarNuevo() {
    try {
        JSONObject json = new JSONObject();
        json.put("CODIGO", Integer.parseInt(CODIGO.getText()));
        json.put("NOMBRES", NOMBRE.getText());
        json.put("DPI", DPI.getText());
        json.put("PUESTO", PUESTO.getText());
        json.put("SALARIO", SALARIO.getText());
        json.put("BONIFICACION", BONIFICACION.getText());
        json.put("IGSS", IGSS.getText());
        json.put("TIPO_CONTRATACION", chkPlanilla.isSelected() ? 1 : 2);
        json.put("ESTADO", 1);
        SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        json.put("FECHA_INGRESO", df.format(FECHAIN.getDate()));

        enviarPOST("http://40.233.19.196/nominapega/empleados", json);

        JOptionPane.showMessageDialog(null, "Empleado creado exitosamente");
        habilitarCampos(false);
        limpiarCampos();
        ListarEmpleados();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
    }
}


public void guardarEdicion() {
    try {
        JSONObject json = new JSONObject();
        json.put("NOMBRES", NOMBRE.getText());
        json.put("DPI", DPI.getText());
        json.put("PUESTO", PUESTO.getText());
        json.put("SALARIO", SALARIO.getText());
        json.put("BONIFICACION", BONIFICACION.getText());
        json.put("IGSS", IGSS.getText());
        json.put("TIPO_CONTRATACION", chkPlanilla.isSelected() ? 1 : 2);
        
        SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        json.put("FECHA_INGRESO", df.format(FECHAIN.getDate()));
        enviarPUT("http://40.233.19.196/nominapega/empleados/" + CODIGO.getText(), json);
        JOptionPane.showMessageDialog(null, "Empleado actualizado");
        habilitarCampos(false);

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
    }
}


/////////////////////////metodos enviar
public void enviarPOST(String urlStr, JSONObject json) throws Exception {
    enviarJSON(urlStr, "POST", json);
}

public void enviarPUT(String urlStr, JSONObject json) throws Exception {
    enviarJSON(urlStr, "PUT", json);
}

public void enviarJSON(String urlStr, String metodo, JSONObject json) throws Exception {
    URL url = new URL(urlStr);
    HttpURLConnection con = (HttpURLConnection) url.openConnection();

    con.setRequestMethod(metodo);
    con.setRequestProperty("Content-Type", "application/json; charset=utf-8");
    con.setDoOutput(true);

    try (OutputStream os = con.getOutputStream()) {
        byte[] input = json.toString().getBytes("utf-8");
        os.write(input, 0, input.length);
    }

    int responseCode = con.getResponseCode();
    if (responseCode != 200) {
        throw new Exception("Error en API: " + responseCode);
    }
}




}
