/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package NuevoInicio;

import Asistencia.Hora_In_Out;
import Asistencia.Reportemensual;
import BodegaPrincipal.DescargaProducto;
import BodegaPrincipal.Gastos;
import BodegaPrincipal.HistorialBP;
import BodegaPrincipal.IngresoProducto;
import BodegaPrincipal.ListadeGastos;
import BodegaPrincipal.ProductoNuevo;
import Encuentro.CargaProductos_Encuentro;
import Encuentro.EliminarPedido_Encuentro;
import Encuentro.HistorialInventario_Encuentro;
import Encuentro.OrdenesFacturadasEncuentro;
import Encuentro.ReporteMensualEncuentro;
import Encuentro.SinFelEncuentro;
import Encuentro.TotalesVentasMes;
import Encuentro.VentasProductos_Encuentro;
import Encuentro.VentasRangoFechas_Encuentro;
import Encuentro.Ventas_Encuentro;
import Gastos.CargaFacturasXML;
import Pinula.CargaProductos_Pinula;
import Pinula.EliminarPedido_Pinula;
import Pinula.HistorialInventario_Pinula;
import Pinula.OrdenesFacturadasPinula;
import Pinula.SinFelPinula;
import Pinula.VentasProductos_Pinula;
import Pinula.VentasRangoFechas_Pinula;
import Pinula.Ventas_Pinula;
import Planilla.Nomina_Empleados;
import Planilla.Nomina_EmpleadosBajas;
import Planilla.Nominas;
import Planilla.Nominas_Historial;
import Planilla.PagoNomina;
import java.awt.Dimension;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author it
 */
public class INICIO extends javax.swing.JFrame {

    /**
     * Creates new form INICIO
     */
    public INICIO() {

        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");

        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException e) {
        }

        initComponents();
        setTitle("Sistema Administracion Inversiones PEGA");
        setDefaultCloseOperation(INICIO.EXIT_ON_CLOSE);

        // ⭐ Maximizamos la ventana
        setExtendedState(INICIO.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Pane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem23 = new javax.swing.JMenuItem();
        jMenuItem24 = new javax.swing.JMenuItem();
        jMenuItem25 = new javax.swing.JMenuItem();
        jMenuItem26 = new javax.swing.JMenuItem();
        jMenuItem30 = new javax.swing.JMenuItem();
        jMenuItem27 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem28 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Pane1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout Pane1Layout = new javax.swing.GroupLayout(Pane1);
        Pane1.setLayout(Pane1Layout);
        Pane1Layout.setHorizontalGroup(
            Pane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1205, Short.MAX_VALUE)
        );
        Pane1Layout.setVerticalGroup(
            Pane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );

        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuBar1.setPreferredSize(new java.awt.Dimension(301, 35));

        jMenu1.setText("EMPLEADOS");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenu1.setMargin(new java.awt.Insets(8, 20, 8, 20));

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/ComponenteImagenes/Paste.png"))); // NOI18N
        jMenu5.setText("ASISTENCIA");
        jMenu5.setMargin(new java.awt.Insets(8, 15, 8, 20));

        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/ComponenteImagenes/Notes.png"))); // NOI18N
        jMenuItem5.setText("REPORTE DE ASISTENCIA");
        jMenuItem5.setMargin(new java.awt.Insets(8, 20, 8, 20));
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem5);

        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/ComponenteImagenes/OK.png"))); // NOI18N
        jMenuItem6.setText("HORAS INGRESO/SALIDAS");
        jMenuItem6.setMargin(new java.awt.Insets(8, 20, 8, 20));
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem6);

        jMenu1.add(jMenu5);

        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/New.png"))); // NOI18N
        jMenuItem7.setText("NOMINA");
        jMenuItem7.setMargin(new java.awt.Insets(8, 15, 8, 20));
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem7);

        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/calculadora.png"))); // NOI18N
        jMenuItem8.setText("AJUSTE EN NOMINA");
        jMenuItem8.setMargin(new java.awt.Insets(8, 15, 8, 20));
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem8);

        jMenuItem22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/ComponenteImagenes/Computer 16x16.png"))); // NOI18N
        jMenuItem22.setText("HISTORIAL NOMINA");
        jMenuItem22.setMargin(new java.awt.Insets(8, 15, 8, 20));
        jMenuItem22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem22ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem22);

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/ComponenteImagenes/Boss.png"))); // NOI18N
        jMenuItem4.setText("EMPLEADOS");
        jMenuItem4.setMargin(new java.awt.Insets(8, 15, 8, 20));
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/ComponenteImagenes/Boss.png"))); // NOI18N
        jMenuItem10.setText("DAR DE BAJA EMPLEADOS");
        jMenuItem10.setMargin(new java.awt.Insets(8, 15, 8, 20));
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem10);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("BODEGA");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenu2.setMargin(new java.awt.Insets(8, 20, 8, 20));

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/New.png"))); // NOI18N
        jMenuItem3.setText("NUEVO PRODUCTO");
        jMenuItem3.setMargin(new java.awt.Insets(8, 15, 8, 20));
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Next.png"))); // NOI18N
        jMenuItem9.setText("INGRESO DE PRODUCTO");
        jMenuItem9.setMargin(new java.awt.Insets(8, 15, 8, 20));
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem9);

        jMenuItem11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/ComponenteImagenes/Download.png"))); // NOI18N
        jMenuItem11.setText("DESCARGA DE PRODUCTO");
        jMenuItem11.setMargin(new java.awt.Insets(8, 15, 8, 20));
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem11);

        jMenuItem12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/ComponenteImagenes/Find.png"))); // NOI18N
        jMenuItem12.setText("CONSULTA INGRESOS/DESCARGAS");
        jMenuItem12.setMargin(new java.awt.Insets(8, 15, 8, 20));
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem12);

        jMenuItem13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/ComponenteImagenes/Dollar.png"))); // NOI18N
        jMenuItem13.setText("GASTOS");
        jMenuItem13.setMargin(new java.awt.Insets(8, 15, 8, 20));
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem13);

        jMenuItem14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/ComponenteImagenes/List.png"))); // NOI18N
        jMenuItem14.setText("LISTAR GASTOS");
        jMenuItem14.setMargin(new java.awt.Insets(8, 15, 8, 20));
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem14);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("PINULA");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenu3.setMargin(new java.awt.Insets(8, 20, 8, 20));

        jMenuItem15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/ComponenteImagenes/Apply.png"))); // NOI18N
        jMenuItem15.setText("VENTAS POR DIA");
        jMenuItem15.setMargin(new java.awt.Insets(8, 15, 8, 20));
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem15);

        jMenuItem16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/ComponenteImagenes/Application.png"))); // NOI18N
        jMenuItem16.setText("TOTAL DE VENTAS ");
        jMenuItem16.setMargin(new java.awt.Insets(8, 15, 8, 20));
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem16);

        jMenuItem17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/ComponenteImagenes/How-to.png"))); // NOI18N
        jMenuItem17.setText("ORDENES POR DIA");
        jMenuItem17.setMargin(new java.awt.Insets(8, 15, 8, 20));
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem17);

        jMenuItem18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/ComponenteImagenes/Cancel.png"))); // NOI18N
        jMenuItem18.setText("CANCELAR OREDENES");
        jMenuItem18.setMargin(new java.awt.Insets(8, 15, 8, 20));
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem18);

        jMenuItem19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/ComponenteImagenes/Buy.png"))); // NOI18N
        jMenuItem19.setText("ORDENES");
        jMenuItem19.setMargin(new java.awt.Insets(8, 15, 8, 20));
        jMenuItem19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem19ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem19);

        jMenuItem20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/ComponenteImagenes/Buy.png"))); // NOI18N
        jMenuItem20.setText("ORDENES FEL");
        jMenuItem20.setMargin(new java.awt.Insets(8, 15, 8, 20));
        jMenuItem20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem20ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem20);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/ComponenteImagenes/Good mark.png"))); // NOI18N
        jMenuItem2.setText("CUADRE INVENTARIO");
        jMenuItem2.setMargin(new java.awt.Insets(8, 15, 8, 20));
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuItem21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/ComponenteImagenes/Hard disk.png"))); // NOI18N
        jMenuItem21.setText("HISTORIAL INVENTARIO");
        jMenuItem21.setMargin(new java.awt.Insets(8, 15, 8, 20));
        jMenuItem21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem21ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem21);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("ENCUENTRO");
        jMenu4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenu4.setMargin(new java.awt.Insets(8, 20, 8, 20));

        jMenuItem23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/ComponenteImagenes/Apply.png"))); // NOI18N
        jMenuItem23.setText("VENTAS POR DIA");
        jMenuItem23.setMargin(new java.awt.Insets(8, 15, 8, 20));
        jMenuItem23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem23ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem23);

        jMenuItem24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/ComponenteImagenes/Pinion.png"))); // NOI18N
        jMenuItem24.setText("TOTAL DE VENTAS ");
        jMenuItem24.setMargin(new java.awt.Insets(8, 15, 8, 20));
        jMenuItem24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem24ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem24);

        jMenuItem25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/ComponenteImagenes/How-to.png"))); // NOI18N
        jMenuItem25.setText("ORDENES POR DIA");
        jMenuItem25.setMargin(new java.awt.Insets(8, 15, 8, 20));
        jMenuItem25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem25ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem25);

        jMenuItem26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/ComponenteImagenes/Cancel.png"))); // NOI18N
        jMenuItem26.setText("CANCELAR OREDENES");
        jMenuItem26.setMargin(new java.awt.Insets(8, 15, 8, 20));
        jMenuItem26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem26ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem26);

        jMenuItem30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/ComponenteImagenes/Buy.png"))); // NOI18N
        jMenuItem30.setText("ORDENES");
        jMenuItem30.setMargin(new java.awt.Insets(8, 15, 8, 20));
        jMenuItem30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem30ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem30);

        jMenuItem27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/ComponenteImagenes/Buy.png"))); // NOI18N
        jMenuItem27.setText("ORDENES FEL");
        jMenuItem27.setMargin(new java.awt.Insets(8, 15, 8, 20));
        jMenuItem27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem27ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem27);

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/ComponenteImagenes/Good mark.png"))); // NOI18N
        jMenuItem1.setText("CUADRE INVENTARIO");
        jMenuItem1.setMargin(new java.awt.Insets(8, 15, 8, 20));
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem1);

        jMenuItem28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/ComponenteImagenes/Hard disk.png"))); // NOI18N
        jMenuItem28.setText("HISTORIAL INVENTARIO");
        jMenuItem28.setMargin(new java.awt.Insets(8, 15, 8, 20));
        jMenuItem28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem28ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem28);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Pane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Pane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        Reportemensual tra = new Reportemensual();
        Pane1.add(tra);
        Dimension desktopSize = Pane1.getSize();
        Dimension FrameSize = tra.getSize();
        tra.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        tra.setVisible(true);

    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed

        Hora_In_Out tra = new Hora_In_Out();
        Pane1.add(tra);
        Dimension desktopSize = Pane1.getSize();
        Dimension FrameSize = tra.getSize();
        tra.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        tra.setVisible(true);

    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        try {
            Nomina_Empleados tra = new Nomina_Empleados();
            Pane1.add(tra);
            Dimension desktopSize = Pane1.getSize();
            Dimension FrameSize = tra.getSize();
            tra.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
            tra.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(INICIO.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        try {
            Nominas tra = new Nominas();
            Pane1.add(tra);
            Dimension desktopSize = Pane1.getSize();
            Dimension FrameSize = tra.getSize();
            tra.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
            tra.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(INICIO.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        try {
            PagoNomina tra = new PagoNomina();
            Pane1.add(tra);
            Dimension desktopSize = Pane1.getSize();
            Dimension FrameSize = tra.getSize();
            tra.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
            tra.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(INICIO.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        try {
            Nomina_EmpleadosBajas tra = new Nomina_EmpleadosBajas();
            Pane1.add(tra);
            Dimension desktopSize = Pane1.getSize();
            Dimension FrameSize = tra.getSize();
            tra.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
            tra.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(INICIO.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        try {
            ProductoNuevo tra = new ProductoNuevo();
            Pane1.add(tra);
            Dimension desktopSize = Pane1.getSize();
            Dimension FrameSize = tra.getSize();
            tra.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
            tra.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(INICIO.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        try {
            IngresoProducto tra = new IngresoProducto();
            Pane1.add(tra);
            Dimension desktopSize = Pane1.getSize();
            Dimension FrameSize = tra.getSize();
            tra.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
            tra.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(INICIO.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        try {
            DescargaProducto tra = new DescargaProducto();
            Pane1.add(tra);
            Dimension desktopSize = Pane1.getSize();
            Dimension FrameSize = tra.getSize();
            tra.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
            tra.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(INICIO.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        try {
            HistorialBP tra = new HistorialBP();
            Pane1.add(tra);
            Dimension desktopSize = Pane1.getSize();
            Dimension FrameSize = tra.getSize();
            tra.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
            tra.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(INICIO.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        try {
            Gastos tra = new Gastos();
            Pane1.add(tra);
            Dimension desktopSize = Pane1.getSize();
            Dimension FrameSize = tra.getSize();
            tra.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
            tra.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(INICIO.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        try {
            ListadeGastos tra = new ListadeGastos();
            Pane1.add(tra);
            Dimension desktopSize = Pane1.getSize();
            Dimension FrameSize = tra.getSize();
            tra.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
            tra.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(INICIO.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        try {
            CargaProductos_Pinula tra = new CargaProductos_Pinula();
            Pane1.add(tra);
            Dimension desktopSize = Pane1.getSize();
            Dimension FrameSize = tra.getSize();
            tra.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
            tra.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(INICIO.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        try {
            Ventas_Pinula tra = new Ventas_Pinula();
            Pane1.add(tra);
            Dimension desktopSize = Pane1.getSize();
            Dimension FrameSize = tra.getSize();
            tra.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
            tra.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(INICIO.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        try {
            VentasRangoFechas_Pinula tra = new VentasRangoFechas_Pinula();
            Pane1.add(tra);
            Dimension desktopSize = Pane1.getSize();
            Dimension FrameSize = tra.getSize();
            tra.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
            tra.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(INICIO.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
        try {
            VentasProductos_Pinula tra = new VentasProductos_Pinula();
            Pane1.add(tra);
            Dimension desktopSize = Pane1.getSize();
            Dimension FrameSize = tra.getSize();
            tra.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
            tra.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(INICIO.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
        try {
            EliminarPedido_Pinula tra = new EliminarPedido_Pinula();
            Pane1.add(tra);
            Dimension desktopSize = Pane1.getSize();
            Dimension FrameSize = tra.getSize();
            tra.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
            tra.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(INICIO.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem18ActionPerformed

    private void jMenuItem19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem19ActionPerformed
        try {
            SinFelPinula tra = new SinFelPinula();
            Pane1.add(tra);
            Dimension desktopSize = Pane1.getSize();
            Dimension FrameSize = tra.getSize();
            tra.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
            tra.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(INICIO.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem19ActionPerformed

    private void jMenuItem20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem20ActionPerformed
        try {
            OrdenesFacturadasPinula tra = new OrdenesFacturadasPinula();
            Pane1.add(tra);
            Dimension desktopSize = Pane1.getSize();
            Dimension FrameSize = tra.getSize();
            tra.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
            tra.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(INICIO.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem20ActionPerformed

    private void jMenuItem21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem21ActionPerformed
        try {
            HistorialInventario_Pinula tra = new HistorialInventario_Pinula();
            Pane1.add(tra);
            Dimension desktopSize = Pane1.getSize();
            Dimension FrameSize = tra.getSize();
            tra.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
            tra.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(INICIO.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem21ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        try {
           CargaProductos_Encuentro tra = new CargaProductos_Encuentro();
            Pane1.add(tra);
            Dimension desktopSize = Pane1.getSize();
            Dimension FrameSize = tra.getSize();
            tra.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
            tra.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(INICIO.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem23ActionPerformed
       try {
             Ventas_Encuentro tra = new Ventas_Encuentro();
            Pane1.add(tra);
            Dimension desktopSize = Pane1.getSize();
            Dimension FrameSize = tra.getSize();
            tra.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
            tra.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(INICIO.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem23ActionPerformed

    private void jMenuItem24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem24ActionPerformed
        try {
            VentasRangoFechas_Encuentro tra = new VentasRangoFechas_Encuentro();
            Pane1.add(tra);
            Dimension desktopSize = Pane1.getSize();
            Dimension FrameSize = tra.getSize();
            tra.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
            tra.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(INICIO.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem24ActionPerformed

    private void jMenuItem30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem30ActionPerformed
        try {
            SinFelEncuentro tra = new SinFelEncuentro();
            Pane1.add(tra);
            Dimension desktopSize = Pane1.getSize();
            Dimension FrameSize = tra.getSize();
            tra.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
            tra.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(INICIO.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem30ActionPerformed

    private void jMenuItem25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem25ActionPerformed
        try {
            VentasProductos_Encuentro tra = new VentasProductos_Encuentro();
            Pane1.add(tra);
            Dimension desktopSize = Pane1.getSize();
            Dimension FrameSize = tra.getSize();
            tra.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
            tra.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(INICIO.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem25ActionPerformed

    private void jMenuItem27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem27ActionPerformed
       try {
            OrdenesFacturadasEncuentro tra = new OrdenesFacturadasEncuentro();
            Pane1.add(tra);
            Dimension desktopSize = Pane1.getSize();
            Dimension FrameSize = tra.getSize();
            tra.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
            tra.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(INICIO.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem27ActionPerformed

    private void jMenuItem26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem26ActionPerformed
        try {
            EliminarPedido_Encuentro tra = new EliminarPedido_Encuentro();
            Pane1.add(tra);
            Dimension desktopSize = Pane1.getSize();
            Dimension FrameSize = tra.getSize();
            tra.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
            tra.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(INICIO.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem26ActionPerformed

    private void jMenuItem28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem28ActionPerformed
        try {
            HistorialInventario_Encuentro tra = new HistorialInventario_Encuentro();
            Pane1.add(tra);
            Dimension desktopSize = Pane1.getSize();
            Dimension FrameSize = tra.getSize();
            tra.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
            tra.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(INICIO.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem28ActionPerformed

    private void jMenuItem22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem22ActionPerformed
        try {
            Nominas_Historial tra = new Nominas_Historial();
            Pane1.add(tra);
            Dimension desktopSize = Pane1.getSize();
            Dimension FrameSize = tra.getSize();
            tra.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
            tra.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(INICIO.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem22ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(INICIO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(INICIO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(INICIO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(INICIO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                INICIO ventana = new INICIO();
                ventana.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Pane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem25;
    private javax.swing.JMenuItem jMenuItem26;
    private javax.swing.JMenuItem jMenuItem27;
    private javax.swing.JMenuItem jMenuItem28;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem30;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    // End of variables declaration//GEN-END:variables
}
