/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Gastos;

import ClasesElRey.BDConexion;
import com.sun.jdi.connect.spi.Connection;
import java.io.File;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;

/**
 *
 * @author it
 */
public class CargaFacturasXML extends javax.swing.JInternalFrame {

    /**
     * Creates new form CargaFacturasXML
     */
     
    JButton btnCargar = new JButton("Cargar facturas XML");
    JTextArea log = new JTextArea(12, 40);

    public CargaFacturasXML() {
        setTitle("Carga de Facturas FEL");
        setSize(500, 350);
        setDefaultCloseOperation(EXIT_ON_CLOSE);

        JScrollPane scroll = new JScrollPane(log);
        log.setEditable(false);

        add(btnCargar, "North");
        add(scroll, "Center");

        btnCargar.addActionListener(e -> seleccionarXML());

    }

    private void seleccionarXML() {
        JFileChooser chooser = new JFileChooser();
        chooser.setMultiSelectionEnabled(true);
        chooser.setFileFilter(
            new javax.swing.filechooser.FileNameExtensionFilter("XML FEL", "xml")
        );

        int res = chooser.showOpenDialog(this);

        if (res == JFileChooser.APPROVE_OPTION) {
            File[] archivos = chooser.getSelectedFiles();
            BDConexion conecta = new BDConexion();
            for (File xml : archivos) {
                try (java.sql.Connection conn = conecta.getConexion()) {
                    FacturaFELParser.procesarXML(xml, conn);
                    log.append("✔ Procesado: " + xml.getName() + "\n");
                } catch (Exception ex) {
                    log.append("✖ Error en " + xml.getName() + ": " + ex.getMessage() + "\n");
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setClosable(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 852, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 455, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
